[build]
  base = "bullionx-web"
  command = "npm ci && npm run build"
  publish = "dist/bullionx-web"

[build.environment]
  NODE_VERSION = "20"

# SPA fallback for Angular routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
